MainApp/urls.py
from django.urls import path


from . import views 

app_name = 'MainApp'

urlpatterns = [
    path('', views.index, name = 'index'),
    path('topics/', views.topics, name = 'topics'),
    path('topics/<int:topic_id>/', views.topic, name = 'topic'),
    path('new_topic/', views.new_topic, name = 'new_topic'),
    path("new_entry/<int:topic_id>/", views.new_entry, name ='new_entry'),
    path("edit_entry/<int:entry_id>/", views.edit_entry, name ='edit_entry')
]


#project url file is the parent file controls what app included, we  can list all url files 
#in master URL file you would like to use include 
#url py files seperates the file 

learning_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('MainApp.urls')), #from the homepage you are gonna include all the url from home page
    path('users/', include("users.urls")),
]

#think this as a parent folder

users/urls.py
from django.urls import path, include
from. import views

app_name = 'users'

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('register/', views.register, name='register'),
]

MainApp/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Topic(models.Model): #inhiritance 
    text = models.CharField(max_length= 200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete = models.CASCADE)
    
    def __str__(self): #string method helps to reutn the topic
        return self.text #this will give the name of the topic
    
    
    
class Entry(models.Model):
    topic = models.ForeignKey(Topic, on_delete = models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    
    
    class Meta:
        verbose_name_plural = 'entries'
    
    
    def __str__(self):
        return f"{self.text[:50]}..." #show only first 50 characters 

users/models.py
from django.db import models
from tabnanny import verbose
# Create your models here.

MainApp/forms.py
from django import forms

from .models import Topic, Entry

class TopicForm(forms.ModelForm):

    class Meta:
        model = Topic
        fields = ['text']
        labels = {'Text: ':''}
        
        
class EntryForm(forms.ModelForm):
    
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'Text: ':''}
        widgets = {'text':forms.Textarea(attrs ={'cols':80})} #altering the text form and makeing it 80 

MainApp/views.py
from django.shortcuts import render, redirect

from .forms import TopicForm, EntryForm

from .models import Topic, Entry

from django.contrib.auth.decorators import login_required

from django.http import Http404
# Create your views here.

def index(request):
    return render(request, 'MainApp/index.html') #process the request and rendering a page in your browser 

@login_required

def topics(request):
    #topics = Topic.objects.order_by("date_added")
    topics = Topic.objects.filter(owner = request.user).order_by("date_added")
    context = {'topics': topics} #key you have to refer in html and value you need to define (above line)
    
    return render(request, 'MainApp/topics.html', context)

@login_required
def topic(request, topic_id):
    topic = Topic.objects.get(id= topic_id)
    if topic.owner != request.user:
        raise Http404
    
    entries = topic.entry_set.all()
    
    context = {'topic': topic, 'entries': entries}
    
    return render(request, 'MainApp/topic.html', context)

'''topic will bring us individual topic page e.g. chess or mountain climbing but topics will bring to 
page for the all the topic; Topic (capital topic) here is the obejct or model'''
'''context - context is dictionary and passes infomration from view to template '''
'''topic and entries are object passes to web page '''
'''types of request: get receive information and post is click submit '''

@login_required
def new_topic(request):
    if request.method != "POST":
        form = TopicForm()
    else:
        form = TopicForm(data = request.POST)
        
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            
            return redirect('MainApp:topics')
        
    context = {'form': form}
    return render(request, 'MainApp/new_topic.html', context)

@login_required
def new_entry(request, topic_id): #this is just an integer 
    topic = Topic.objects.get(id=topic_id)  #this is a topic object
    
    if topic.owner != request.user:
        raise Http404
    
    if request.method != 'POST':
        form = EntryForm()
        
    else:
        form = EntryForm (data = request.POST)
        
        if form.is_valid():
            new_entry = form.save(commit = False)
            new_entry.topic = topic
            new_entry.save()
            return redirect('MainApp:topic', topic_id = topic_id)
        
    context = {'form': form, 'topic': topic}
    return render(request, 'MainApp/new_entry.html', context)
 
@login_required
def edit_entry(request, entry_id):
    entry =Entry.objects.get(id = entry_id)
    topic = entry.topic
    
    if topic.owner != request.user:
        raise Http404
    if request.method != 'POST':
        form = EntryForm(instance = entry)
         
    else:
        form = EntryForm(instance = entry, data = request.POST)
         
        if form.is_valid():
            form.save()
            return redirect ('MainApp:topic', topic_id = topic.id)
        
    context = {'form': form, 'topic': topic, 'entry': entry}
    return render(request, 'MainApp/edit_entry.html', context)  

     

users/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm


# Create your views here.

def register(request):
    # register a new user
    if request.method != 'POST':
        form = UserCreationForm() # display blank registration form
    else:
        form = UserCreationForm(data=request.POST) # process completed form
        if form.is_valid():
            new_user = form.save()
            login(request, new_user)
            return redirect('MainApp:index')
   
    context = {'form': form}
    return render(request, 'registration/register.html', context)

MainApp/templates/mainapp/base.html
<p>

    <a href="{% url 'MainApp:index' %}">Learning Log </a>
    <a href="{% url 'MainApp:topics' %}">Topics </a>


    {% if user.is_authenticated %}
    Hello, {{ user.username }}.
    <a href="{% url 'users:logout' %}">Log out </a>
    {% else %}
    <a href="{% url 'users:register' %}">Register </a>
    <a href="{% url 'users:login' %}">Log in </a>
    {% endif %}


</p>

{% block content %}

{% endblock content %}

MainApp/templates/mainapp/edit_entry.html
{% extends "MainApp/base.html"%}

{% block content %}
<p><a href = "{% url 'MainApp:topic' topic.id %}">{{ topic }}</a></p>

<p>Edit entry: </p>

<form action="{% url 'MainApp:edit_entry' entry.id %}" method='post'> 
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Save Changes</button>


</form>

{% endblock content %}

MainApp/templates/mainapp/index.html
{% extends "MainApp/base.html"%}

{%block content%}

<p> Learning Log helps you keep track of your learning, 
    for any topic you're learning about.

</p>

{% endblock content %}

MainApp/templates/mainapp/new_entry.html
{% extends "MainApp/base.html"%}

{% block content %}
<p>
    <a href = "{% url 'MainApp:topic' topic.id %}">{{ topic }}</a>
</p>

<p>Add a new entry:</p>

<form action="{% url 'MainApp:new_entry' topic.id %}" method='post'> 
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Add entry</button>


</form>

{% endblock content %}

MainApp/templates/mainapp/new_topic.html
{% extends "MainApp/base.html"%}

{% block content %}

<p>Add a new topic:</p>

<form action="{% url 'MainApp:new_topic' %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Add topic</button>


</form>

{% endblock content %}

MainApp/templates/mainapp/topic.html
{% extends "MainApp/base.html"%}

{%block content%}

<p>Topic: {{ topic }}</p>
<!--topic is from context dictionary-->

<ul>
    <li>
        {% for e in entries %}
        <p>{{ e.text }}</p> <!--we can call any attributes-->
        <p>{{ e.date_added }}</p>
        <p><a href ="{% url 'MainApp:edit_entry' e.id %}"> Edit entry<a/></p>
    <li>
    {% empty %}
    <li>There are no entries for this topic yet.</li>

    {% endfor %}

</ul>
 
<p><a href = "{% url 'MainApp:new_entry' topic.id %}">Add New Entry<a/></p>

{% endblock content %}

MainApp/templates/mainapp/topics.html
{% extends "MainApp/base.html"%}

{% block content %}



<ul>
    {% for t in topics %}

    <li> 
        <a href="{% url 'MainApp:topic' t.id %}"> {{ t }}</a>
    </li>

    {% empty %}

    <li> No topics have been added yet.</li>
    {% endfor %}

<ul>
    <a href="{% url 'MainApp:new_topic' %}">Add a new topic</a>



{% endblock content%}